@baseUrl = http://localhost:3000

# RECADOS
### Lista todos os recados
GET {{baseUrl}}/recados/
?limit=0
&offset=0

### Lista apenas um recado
GET {{baseUrl}}/recados/2/

### Cria um recado
POST {{baseUrl}}/recados/
Content-Type: application/json

{
"texto": "Novo Recado",
"de": "Joana",
"para": "João"
}

### Atualiza um recado
PATCH {{baseUrl}}/recados/2/
Content-Type: application/json

{
"texto": "Recado",
"lido": true
}

### Apaga um recado
DELETE {{baseUrl}}/recados/2/


#


# Pessoas
### Lista todas pessoas.
GET {{baseUrl}}/pessoas/
?limit=0
&offset=0

### Lista apenas uma Pessoa
GET {{baseUrl}}/pessoas/2/

### Cria uma pessoa
POST {{baseUrl}}/pessoas/
Content-Type: application/json

{
"nome": "Luiz",
"email": "email1@email.com",
"password": "123456"

}

### Atualiza uma pessoa
PATCH {{baseUrl}}/pessoas/2/
Content-Type: application/json

{
"texto": "Recado",
"lido": true
}

### Apaga uma pessoa
DELETE {{baseUrl}}/pessoas/2/